services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:15
    container_name: ponto_db
    environment:
      POSTGRES_USER: ${DB_USER} # <-- MODIFICADO
      POSTGRES_PASSWORD: ${DB_PASSWORD} # <-- MODIFICADO
      POSTGRES_DB: registroponto_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Serviço do Back-end Spring Boot (Java)
  backend:
    container_name: ponto-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}" # <-- MODIFICADO
    environment:
      - spring.datasource.url=${DB_URL} # <-- MODIFICADO
      - spring.datasource.username=${DB_USER} # <-- MODIFICADO
      - spring.datasource.password=${DB_PASSWORD} # <-- MODIFICADO
      - server.port=${BACKEND_PORT} # <-- MODIFICADO
      - server.forward-headers-strategy=NATIVE
    depends_on:
      - db

  # Serviço do Front-end (React + Nginx)
  frontend:
    container_name: ponto-frontend
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres-data: